# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "prometheus.rules.yml"

scrape_configs:
  - job_name: 'cleanarchitectureapi'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: /metrics-text