apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: metricsdatabase
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: true
    editable: true